// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSeer.Data;

#nullable disable

namespace TheSeer.Migrations
{
    [DbContext(typeof(TheSeerDbContext))]
    [Migration("20251226105432_CardsForSeerDeck")]
    partial class CardsForSeerDeck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheSeer.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SuitOrGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Fool",
                            SuitOrGroup = "Major Arcana",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Magician",
                            SuitOrGroup = "Major Arcana",
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The High Priestess",
                            SuitOrGroup = "Major Arcana",
                            Value = 2
                        },
                        new
                        {
                            Id = 4,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Empress",
                            SuitOrGroup = "Major Arcana",
                            Value = 3
                        },
                        new
                        {
                            Id = 5,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Emperor",
                            SuitOrGroup = "Major Arcana",
                            Value = 4
                        },
                        new
                        {
                            Id = 6,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Hierophant",
                            SuitOrGroup = "Major Arcana",
                            Value = 5
                        },
                        new
                        {
                            Id = 7,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Lovers",
                            SuitOrGroup = "Major Arcana",
                            Value = 6
                        },
                        new
                        {
                            Id = 8,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Chariot",
                            SuitOrGroup = "Major Arcana",
                            Value = 7
                        },
                        new
                        {
                            Id = 9,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Strength",
                            SuitOrGroup = "Major Arcana",
                            Value = 8
                        },
                        new
                        {
                            Id = 10,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Hermit",
                            SuitOrGroup = "Major Arcana",
                            Value = 9
                        },
                        new
                        {
                            Id = 11,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Wheel of Fortune",
                            SuitOrGroup = "Major Arcana",
                            Value = 10
                        },
                        new
                        {
                            Id = 12,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Justice",
                            SuitOrGroup = "Major Arcana",
                            Value = 11
                        },
                        new
                        {
                            Id = 13,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Hanged Man",
                            SuitOrGroup = "Major Arcana",
                            Value = 12
                        },
                        new
                        {
                            Id = 14,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Death",
                            SuitOrGroup = "Major Arcana",
                            Value = 13
                        },
                        new
                        {
                            Id = 15,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Temperance",
                            SuitOrGroup = "Major Arcana",
                            Value = 14
                        },
                        new
                        {
                            Id = 16,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Devil",
                            SuitOrGroup = "Major Arcana",
                            Value = 15
                        },
                        new
                        {
                            Id = 17,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Tower",
                            SuitOrGroup = "Major Arcana",
                            Value = 16
                        },
                        new
                        {
                            Id = 18,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Star",
                            SuitOrGroup = "Major Arcana",
                            Value = 17
                        },
                        new
                        {
                            Id = 19,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Moon",
                            SuitOrGroup = "Major Arcana",
                            Value = 18
                        },
                        new
                        {
                            Id = 20,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The Sun",
                            SuitOrGroup = "Major Arcana",
                            Value = 19
                        },
                        new
                        {
                            Id = 21,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Judgement",
                            SuitOrGroup = "Major Arcana",
                            Value = 20
                        },
                        new
                        {
                            Id = 22,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "The World",
                            SuitOrGroup = "Major Arcana",
                            Value = 21
                        },
                        new
                        {
                            Id = 23,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ace of Trees",
                            SuitOrGroup = "Trees",
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Two of Trees",
                            SuitOrGroup = "Trees",
                            Value = 2
                        },
                        new
                        {
                            Id = 25,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Three of Trees",
                            SuitOrGroup = "Trees",
                            Value = 3
                        },
                        new
                        {
                            Id = 26,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Four of Trees",
                            SuitOrGroup = "Trees",
                            Value = 4
                        },
                        new
                        {
                            Id = 27,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Five of Trees",
                            SuitOrGroup = "Trees",
                            Value = 5
                        },
                        new
                        {
                            Id = 28,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Six of Trees",
                            SuitOrGroup = "Trees",
                            Value = 6
                        },
                        new
                        {
                            Id = 29,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Seven of Trees",
                            SuitOrGroup = "Trees",
                            Value = 7
                        },
                        new
                        {
                            Id = 30,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Eight of Trees",
                            SuitOrGroup = "Trees",
                            Value = 8
                        },
                        new
                        {
                            Id = 31,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Nine of Trees",
                            SuitOrGroup = "Trees",
                            Value = 9
                        },
                        new
                        {
                            Id = 32,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ten of Trees",
                            SuitOrGroup = "Trees",
                            Value = 10
                        },
                        new
                        {
                            Id = 33,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Page of Trees",
                            SuitOrGroup = "Trees",
                            Value = 11
                        },
                        new
                        {
                            Id = 34,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Knight of Trees",
                            SuitOrGroup = "Trees",
                            Value = 12
                        },
                        new
                        {
                            Id = 35,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Queen of Trees",
                            SuitOrGroup = "Trees",
                            Value = 13
                        },
                        new
                        {
                            Id = 36,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "King of Trees",
                            SuitOrGroup = "Trees",
                            Value = 14
                        },
                        new
                        {
                            Id = 37,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ace of Books",
                            SuitOrGroup = "Books",
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Two of Books",
                            SuitOrGroup = "Books",
                            Value = 2
                        },
                        new
                        {
                            Id = 39,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Three of Books",
                            SuitOrGroup = "Books",
                            Value = 3
                        },
                        new
                        {
                            Id = 40,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Four of Books",
                            SuitOrGroup = "Books",
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Five of Books",
                            SuitOrGroup = "Books",
                            Value = 5
                        },
                        new
                        {
                            Id = 42,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Six of Books",
                            SuitOrGroup = "Books",
                            Value = 6
                        },
                        new
                        {
                            Id = 43,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Seven of Books",
                            SuitOrGroup = "Books",
                            Value = 7
                        },
                        new
                        {
                            Id = 44,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Eight of Books",
                            SuitOrGroup = "Books",
                            Value = 8
                        },
                        new
                        {
                            Id = 45,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Nine of Books",
                            SuitOrGroup = "Books",
                            Value = 9
                        },
                        new
                        {
                            Id = 46,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ten of Books",
                            SuitOrGroup = "Books",
                            Value = 10
                        },
                        new
                        {
                            Id = 47,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Page of Books",
                            SuitOrGroup = "Books",
                            Value = 11
                        },
                        new
                        {
                            Id = 48,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Knight of Books",
                            SuitOrGroup = "Books",
                            Value = 12
                        },
                        new
                        {
                            Id = 49,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Queen of Books",
                            SuitOrGroup = "Books",
                            Value = 13
                        },
                        new
                        {
                            Id = 50,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "King of Books",
                            SuitOrGroup = "Books",
                            Value = 14
                        },
                        new
                        {
                            Id = 51,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ace of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 1
                        },
                        new
                        {
                            Id = 52,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Two of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 2
                        },
                        new
                        {
                            Id = 53,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Three of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 3
                        },
                        new
                        {
                            Id = 54,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Four of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 4
                        },
                        new
                        {
                            Id = 55,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Five of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 5
                        },
                        new
                        {
                            Id = 56,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Six of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 6
                        },
                        new
                        {
                            Id = 57,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Seven of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 7
                        },
                        new
                        {
                            Id = 58,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Eight of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 8
                        },
                        new
                        {
                            Id = 59,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Nine of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 9
                        },
                        new
                        {
                            Id = 60,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ten of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 10
                        },
                        new
                        {
                            Id = 61,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Page of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 11
                        },
                        new
                        {
                            Id = 62,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Knight of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 12
                        },
                        new
                        {
                            Id = 63,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Queen of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 13
                        },
                        new
                        {
                            Id = 64,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "King of Teeth",
                            SuitOrGroup = "Teeth",
                            Value = 14
                        },
                        new
                        {
                            Id = 65,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ace of Ores",
                            SuitOrGroup = "Ores",
                            Value = 1
                        },
                        new
                        {
                            Id = 66,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Two of Ores",
                            SuitOrGroup = "Ores",
                            Value = 2
                        },
                        new
                        {
                            Id = 67,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Three of Ores",
                            SuitOrGroup = "Ores",
                            Value = 3
                        },
                        new
                        {
                            Id = 68,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Four of Ores",
                            SuitOrGroup = "Ores",
                            Value = 4
                        },
                        new
                        {
                            Id = 69,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Five of Ores",
                            SuitOrGroup = "Ores",
                            Value = 5
                        },
                        new
                        {
                            Id = 70,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Six of Ores",
                            SuitOrGroup = "Ores",
                            Value = 6
                        },
                        new
                        {
                            Id = 71,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Seven of Ores",
                            SuitOrGroup = "Ores",
                            Value = 7
                        },
                        new
                        {
                            Id = 72,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Eight of Ores",
                            SuitOrGroup = "Ores",
                            Value = 8
                        },
                        new
                        {
                            Id = 73,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Nine of Ores",
                            SuitOrGroup = "Ores",
                            Value = 9
                        },
                        new
                        {
                            Id = 74,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Ten of Ores",
                            SuitOrGroup = "Ores",
                            Value = 10
                        },
                        new
                        {
                            Id = 75,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Page of Ores",
                            SuitOrGroup = "Ores",
                            Value = 11
                        },
                        new
                        {
                            Id = 76,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Knight of Ores",
                            SuitOrGroup = "Ores",
                            Value = 12
                        },
                        new
                        {
                            Id = 77,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "Queen of Ores",
                            SuitOrGroup = "Ores",
                            Value = 13
                        },
                        new
                        {
                            Id = 78,
                            DeckId = 1,
                            ImageKey = "",
                            Name = "King of Ores",
                            SuitOrGroup = "Ores",
                            Value = 14
                        });
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetFolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CardBackImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Creator")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("DateOfPublish")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SystemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemTypeId");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetFolder = " ",
                            CardBackImage = " ",
                            Creator = "Elvira Mariesdotter",
                            DateOfPublish = new DateOnly(2025, 12, 25),
                            Description = "The deck the seer herself carved out of the sandstone in her lands. Carries specific suits and meanings. Can create somewhat harsh readings, but always true and with good intent.",
                            IsLocked = false,
                            Name = "The Seer's deck",
                            SystemTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetFolder = " ",
                            CardBackImage = " ",
                            Creator = "Casey Gilly",
                            DateOfPublish = new DateOnly(2022, 8, 28),
                            Description = "A Lord of the Rings inspired tarot deck, replacing the pentacle suit with rings instead. All Major arcana and clothed cards are named after characters from the Realm of J.R.R. Tolkien. Illustrations by Tomas Hijo.",
                            IsLocked = false,
                            Name = "Lord of the Rings Tarot",
                            SystemTypeId = 1
                        });
                });

            modelBuilder.Entity("TheSeer.Domain.Models.DrawnCard", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpreadPositionId")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DrawOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("UserNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReadingId", "SpreadPositionId");

                    b.HasIndex("CardId");

                    b.HasIndex("SpreadPositionId");

                    b.HasIndex("ReadingId", "CardId")
                        .IsUnique();

                    b.ToTable("DrawnCards");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.FavoriteDeck", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "DeckId");

                    b.HasIndex("DeckId");

                    b.ToTable("FavoriteDecks");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateWritten")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId");

                    b.HasIndex("UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Meaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpreadId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserMood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("SpreadId");

                    b.HasIndex("UserId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Spread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageOverlay")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SystemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemTypeId");

                    b.ToTable("Spreads");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SpreadPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("SpreadId")
                        .HasColumnType("int");

                    b.Property<int>("XPos")
                        .HasColumnType("int");

                    b.Property<int>("YPos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpreadId");

                    b.ToTable("SpreadPositions");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SystemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeReversed")
                        .HasColumnType("bit");

                    b.Property<int>("DefaultCardCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SystemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanBeReversed = true,
                            DefaultCardCount = 78,
                            Description = "The classical system for introspection, guidance and spirital development. Usually has 78 cards, always divided into the major and minor arcana.",
                            Name = "Tarot"
                        },
                        new
                        {
                            Id = 2,
                            CanBeReversed = true,
                            DefaultCardCount = 24,
                            Description = "An old norse system built upon the old futhark of 24 runes. Each rune symbolize natural powers and gods or godesses. Used to interpret hidden energies and bigger happenings in life.",
                            Name = "Runes"
                        },
                        new
                        {
                            Id = 3,
                            CanBeReversed = false,
                            DefaultCardCount = 44,
                            Description = "A free and intuitive system for guidance. Not as strict as the Tarot system. Usually have unique themes, and can be flexible regarding card count.",
                            Name = "Oracle"
                        });
                });

            modelBuilder.Entity("TheSeer.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Card", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Deck", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.SystemType", "SystemType")
                        .WithMany("Decks")
                        .HasForeignKey("SystemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.DrawnCard", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Card", "Card")
                        .WithMany("DrawnCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.Reading", "Reading")
                        .WithMany("DrawnCards")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.SpreadPosition", "SpreadPosition")
                        .WithMany("DrawnCards")
                        .HasForeignKey("SpreadPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Reading");

                    b.Navigation("SpreadPosition");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.FavoriteDeck", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("FavoriteDecks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.User", "User")
                        .WithMany("FavoriteDecks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.JournalEntry", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Reading", "Reading")
                        .WithMany("JournalEntries")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.User", "User")
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Meaning", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Card", "Card")
                        .WithMany("Meanings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("Meanings")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Reading", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("Readings")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.Spread", "Spread")
                        .WithMany("Readings")
                        .HasForeignKey("SpreadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.User", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Spread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Spread", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.SystemType", "SystemType")
                        .WithMany("Spreads")
                        .HasForeignKey("SystemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SpreadPosition", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Spread", "Spread")
                        .WithMany("SpreadPositions")
                        .HasForeignKey("SpreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spread");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Card", b =>
                {
                    b.Navigation("DrawnCards");

                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Deck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("FavoriteDecks");

                    b.Navigation("Meanings");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Reading", b =>
                {
                    b.Navigation("DrawnCards");

                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Spread", b =>
                {
                    b.Navigation("Readings");

                    b.Navigation("SpreadPositions");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SpreadPosition", b =>
                {
                    b.Navigation("DrawnCards");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SystemType", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Spreads");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.User", b =>
                {
                    b.Navigation("FavoriteDecks");

                    b.Navigation("JournalEntries");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
