// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheSeer.Data;

#nullable disable

namespace TheSeer.Migrations
{
    [DbContext(typeof(TheSeerDbContext))]
    partial class TheSeerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheSeer.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SuitOrGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetFolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CardBackImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Creator")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("DateOfPublish")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SystemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemTypeId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.DrawnCard", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpreadPositionId")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("DrawOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("UserNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReadingId", "SpreadPositionId");

                    b.HasIndex("CardId");

                    b.HasIndex("SpreadPositionId");

                    b.HasIndex("ReadingId", "CardId")
                        .IsUnique();

                    b.ToTable("DrawnCards");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.FavoriteDeck", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId", "DeckId");

                    b.HasIndex("DeckId");

                    b.ToTable("FavoriteDecks");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateWritten")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId");

                    b.HasIndex("UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Meaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpreadId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserMood")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("SpreadId");

                    b.HasIndex("UserId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Spread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageOverlay")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SystemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemTypeId");

                    b.ToTable("Spreads");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SpreadPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("SpreadId")
                        .HasColumnType("int");

                    b.Property<int>("XPos")
                        .HasColumnType("int");

                    b.Property<int>("YPos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpreadId");

                    b.ToTable("SpreadPositions");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SystemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeReversed")
                        .HasColumnType("bit");

                    b.Property<int>("DefaultCardCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SystemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanBeReversed = true,
                            DefaultCardCount = 78,
                            Description = "The classical system for introspection, guidance and spirital development. Usually has 78 cards, always divided into the major and minor arcana.",
                            Name = "Tarot"
                        },
                        new
                        {
                            Id = 2,
                            CanBeReversed = true,
                            DefaultCardCount = 24,
                            Description = "An old norse system built upon the old futhark of 24 runes. Each rune symbolize natural powers and gods or godesses. Used to interpret hidden energies and bigger happenings in life.",
                            Name = "Runes"
                        },
                        new
                        {
                            Id = 3,
                            CanBeReversed = false,
                            DefaultCardCount = 44,
                            Description = "A free and intuitive system for guidance. Not as strict as the Tarot system. Usually have unique themes, and can be flexible regarding card count.",
                            Name = "Oracle"
                        });
                });

            modelBuilder.Entity("TheSeer.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Card", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Deck", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.SystemType", "SystemType")
                        .WithMany("Decks")
                        .HasForeignKey("SystemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.DrawnCard", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Card", "Card")
                        .WithMany("DrawnCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.Reading", "Reading")
                        .WithMany("DrawnCards")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.SpreadPosition", "SpreadPosition")
                        .WithMany("DrawnCards")
                        .HasForeignKey("SpreadPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Reading");

                    b.Navigation("SpreadPosition");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.FavoriteDeck", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("FavoriteDecks")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.User", "User")
                        .WithMany("FavoriteDecks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.JournalEntry", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Reading", "Reading")
                        .WithMany("JournalEntries")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.User", "User")
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Meaning", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Card", "Card")
                        .WithMany("Meanings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("Meanings")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Reading", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Deck", "Deck")
                        .WithMany("Readings")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.Spread", "Spread")
                        .WithMany("Readings")
                        .HasForeignKey("SpreadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheSeer.Domain.Models.User", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Spread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Spread", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.SystemType", "SystemType")
                        .WithMany("Spreads")
                        .HasForeignKey("SystemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SpreadPosition", b =>
                {
                    b.HasOne("TheSeer.Domain.Models.Spread", "Spread")
                        .WithMany("SpreadPositions")
                        .HasForeignKey("SpreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spread");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Card", b =>
                {
                    b.Navigation("DrawnCards");

                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Deck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("FavoriteDecks");

                    b.Navigation("Meanings");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Reading", b =>
                {
                    b.Navigation("DrawnCards");

                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.Spread", b =>
                {
                    b.Navigation("Readings");

                    b.Navigation("SpreadPositions");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SpreadPosition", b =>
                {
                    b.Navigation("DrawnCards");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.SystemType", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Spreads");
                });

            modelBuilder.Entity("TheSeer.Domain.Models.User", b =>
                {
                    b.Navigation("FavoriteDecks");

                    b.Navigation("JournalEntries");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
